# Generated by Django 6.0.4 on 2026-04-21 08:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_staff_is_active_alter_staff_unique_together'),
        ('pms', '0009_booking_guest'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestFolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='folio', to='pms.booking')),
            ],
            options={
                'verbose_name': 'Guest Folio',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FolioCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_type', models.CharField(choices=[('room', 'Room'), ('restaurant', 'Restaurant'), ('laundry', 'Laundry'), ('spa', 'Spa'), ('minibar', 'Minibar'), ('transport', 'Transport'), ('extra', 'Extra / Miscellaneous')], default='room', max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_charges', to='accounts.staff')),
                ('folio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='billing.guestfolio')),
            ],
            options={
                'verbose_name': 'Folio Charge',
                'ordering': ['date', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='BillingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Credit / Debit Card'), ('upi', 'UPI'), ('online', 'Online Transfer'), ('ota', 'OTA Prepaid'), ('cheque', 'Cheque'), ('razorpay', 'Razorpay')], max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_payments', to='accounts.staff')),
                ('folio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.guestfolio')),
            ],
            options={
                'verbose_name': 'Billing Payment',
                'ordering': ['received_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('partial', 'Partially Paid'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('folio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='billing.guestfolio')),
            ],
            options={
                'verbose_name': 'Invoice',
                'ordering': ['-generated_at'],
            },
        ),
    ]
