# Generated by Django 5.1.6 on 2026-05-04 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_billingpayment_id_alter_foliocharge_id_and_more'),
        ('restaurant', '0004_tablereservation_restaurantorder_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingpayment',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='restaurant.restaurantorder'),
        ),
        migrations.AddField(
            model_name='billingpayment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billingpayment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='billingpayment',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='billingpayment',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='billingpayment',
            name='folio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.guestfolio'),
        ),
        migrations.AlterField(
            model_name='billingpayment',
            name='method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('card', 'Credit / Debit Card'), ('upi', 'UPI'), ('online', 'Online Transfer'), ('ota', 'OTA Prepaid'), ('cheque', 'Cheque'), ('razorpay', 'Razorpay')], max_length=20, null=True),
        ),
    ]
