# Generated by Django 5.1.6 on 2026-05-16 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_subscriptionplan_tagline'),
        ('billing', '0004_billingpayment_order_billingpayment_paid_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_invoices', to='accounts.staff'),
        ),
    ]
