# Generated by Django 5.1.6 on 2026-06-02 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pms', '0016_payment_amount_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTAChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('channel_type', models.CharField(choices=[('booking_com', 'Booking.com'), ('airbnb', 'Airbnb'), ('expedia', 'Expedia'), ('ical', 'iCal Generic')], max_length=30)),
                ('api_key', models.CharField(blank=True, max_length=300)),
                ('api_secret', models.CharField(blank=True, max_length=300)),
                ('ical_url', models.URLField(blank=True)),
                ('hotel_id_on_ota', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('sync_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OTABooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ota_reservation_id', models.CharField(max_length=200, unique=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('new', 'New'), ('modified', 'Modified'), ('cancelled', 'Cancelled'), ('processed', 'Processed')], default='new', max_length=20)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pms.booking')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ota_bookings', to='channelmanager.otachannel')),
            ],
        ),
        migrations.CreateModel(
            name='ChannelRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_stay', models.IntegerField(default=1)),
                ('available_rooms', models.IntegerField(default=0)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pms.room')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='channelmanager.otachannel')),
            ],
            options={
                'unique_together': {('channel', 'room_type', 'date')},
            },
        ),
    ]
