# Generated by Django 5.1.6 on 2026-06-02 11:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_staff_bank_account_staff_esi_number_staff_ifsc_and_more'),
        ('channelmanager', '0001_initial'),
        ('pms', '0016_payment_amount_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otabooking',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='otabooking',
            name='channel',
        ),
        migrations.AlterModelOptions(
            name='otachannel',
            options={'verbose_name': 'OTA Channel'},
        ),
        migrations.AddField(
            model_name='channelrate',
            name='last_pushed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='channelrate',
            name='max_stay',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='channelrate',
            name='ota_channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='channelmanager.otachannel'),
        ),
        migrations.AddField(
            model_name='channelrate',
            name='push_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='channelrate',
            name='stop_sell',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='otachannel',
            name='auth_method',
            field=models.CharField(choices=[('api_key', 'API Key / Secret'), ('oauth2', 'OAuth 2.0'), ('ical', 'iCal (no auth)'), ('webhook', 'Webhook Only')], default='api_key', max_length=20),
        ),
        migrations.AddField(
            model_name='otachannel',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ota_channels', to='accounts.hotel'),
        ),
        migrations.AddField(
            model_name='otachannel',
            name='ical_push_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='otachannel',
            name='oauth_access_token',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='otachannel',
            name='oauth_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otachannel',
            name='oauth_refresh_token',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='otachannel',
            name='property_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='otachannel',
            name='pull_bookings',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='otachannel',
            name='push_availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='otachannel',
            name='push_rates',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='otachannel',
            name='sync_days_ahead',
            field=models.PositiveIntegerField(default=90),
        ),
        migrations.AddField(
            model_name='otachannel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='otachannel',
            name='webhook_secret',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='channelrate',
            name='available_rooms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='channelrate',
            name='min_stay',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='channelrate',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_rates', to='pms.room'),
        ),
        migrations.AlterField(
            model_name='otachannel',
            name='api_key',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='otachannel',
            name='api_secret',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='otachannel',
            name='channel_type',
            field=models.CharField(choices=[('booking_com', 'Booking.com'), ('airbnb', 'Airbnb'), ('expedia', 'Expedia'), ('ical', 'iCal Generic'), ('agoda', 'Agoda'), ('mmt', 'MakeMyTrip'), ('goibibo', 'Goibibo'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='otachannel',
            unique_together={('hotel', 'channel_type', 'hotel_id_on_ota')},
        ),
        migrations.CreateModel(
            name='WebsiteChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200)),
                ('base_url', models.URLField()),
                ('inbound_api_key', models.CharField(default=uuid.uuid4, max_length=128, unique=True)),
                ('callback_url', models.URLField(blank=True)),
                ('outbound_api_key', models.CharField(blank=True, max_length=128)),
                ('sync_availability', models.BooleanField(default=True)),
                ('sync_interval_minutes', models.PositiveIntegerField(default=15)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('sync_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='website_channel', to='accounts.hotel')),
            ],
            options={
                'verbose_name': 'Website Channel',
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(blank=True, max_length=100)),
                ('headers', models.JSONField(default=dict)),
                ('payload', models.JSONField(default=dict)),
                ('raw_body', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed'), ('ignored', 'Ignored')], default='pending', max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='pms.booking')),
                ('ota_channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhook_events', to='channelmanager.otachannel')),
                ('website_channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhook_events', to='channelmanager.websitechannel')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('push', 'Push (ERP → Channel)'), ('pull', 'Pull (Channel → ERP)')], max_length=10)),
                ('entity', models.CharField(choices=[('rate', 'Rate/Availability'), ('booking', 'Booking'), ('cancellation', 'Cancellation')], max_length=20)),
                ('outcome', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], max_length=10)),
                ('records_sent', models.PositiveIntegerField(default=0)),
                ('records_failed', models.PositiveIntegerField(default=0)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ota_channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='channelmanager.otachannel')),
                ('website_channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='channelmanager.websitechannel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='channelrate',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='channelrate',
            name='website_channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='channelmanager.websitechannel'),
        ),
        migrations.AlterUniqueTogether(
            name='channelrate',
            unique_together={('ota_channel', 'website_channel', 'room_type', 'date')},
        ),
        migrations.AddIndex(
            model_name='channelrate',
            index=models.Index(fields=['date', 'room_type'], name='channelmana_date_f968c7_idx'),
        ),
        migrations.DeleteModel(
            name='OTABooking',
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['status'], name='channelmana_status_13977e_idx'),
        ),
        migrations.RemoveField(
            model_name='channelrate',
            name='channel',
        ),
    ]
