# Generated by Django 5.1.6 on 2026-06-03 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channelmanager', '0002_remove_otabooking_booking_remove_otabooking_channel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='websitechannel',
            options={},
        ),
        migrations.RemoveField(
            model_name='websitechannel',
            name='inbound_api_key',
        ),
        migrations.AddField(
            model_name='websitechannel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='websitechannel',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
