# Generated by Django 5.1.6 on 2026-06-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channelmanager', '0003_alter_websitechannel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitechannel',
            name='inbound_api_key',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
