# Generated by Django 5.1.6 on 2026-06-04 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_staff_bank_account_staff_esi_number_staff_ifsc_and_more'),
        ('channelmanager', '0004_websitechannel_inbound_api_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedWebsiteChannelKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inbound_api_key', models.CharField(max_length=64)),
                ('deleted_at', models.DateTimeField()),
                ('hotel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deleted_channel_key', to='accounts.hotel')),
            ],
            options={
                'verbose_name': 'Deleted Website Channel Key',
            },
        ),
    ]
