# Generated by Django 5.1.6 on 2026-06-04 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channelmanager', '0005_deletedwebsitechannelkey'),
        ('pms', '0016_payment_amount_paid'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='channelrate',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='channelrate',
            name='cancellation_policy',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='channelrate',
            name='is_refundable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='channelrate',
            name='rate_plan_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='channelrate',
            name='rate_plan_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='otachannel',
            name='oauth_token_endpoint',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='otachannel',
            name='protocol',
            field=models.CharField(choices=[('json_rest', 'JSON REST'), ('ota_xml', 'OTA XML (Booking.com style)'), ('ical', 'iCal')], default='json_rest', max_length=20),
        ),
        migrations.AddField(
            model_name='otachannel',
            name='supports_webhook',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='otachannel',
            name='sync_interval_minutes',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='otachannel',
            name='webhook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='channelrate',
            unique_together={('ota_channel', 'website_channel', 'room_type', 'date', 'rate_plan_id')},
        ),
        migrations.CreateModel(
            name='OTARoomMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ota_room_id', models.CharField(max_length=100)),
                ('ota_room_name', models.CharField(max_length=200)),
                ('ota_rate_plan_id', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('internal_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ota_mappings', to='pms.room')),
                ('ota_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_mappings', to='channelmanager.otachannel')),
            ],
            options={
                'verbose_name': 'OTA Room Mapping',
                'unique_together': {('ota_channel', 'internal_room')},
            },
        ),
    ]
