# Generated by Django 5.1.6 on 2026-06-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channelmanager', '0006_alter_channelrate_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='synclog',
            name='date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='synclog',
            name='date_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='synclog',
            name='ota_response',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='synclog',
            name='room_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
