# Generated by Django 6.0.4 on 2026-04-17 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Amenity',
            new_name='Property',
        ),
    ]
