# Generated by Django 6.0.4 on 2026-04-17 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0002_rename_amenity_property'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='roomunit',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='property',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='room',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='roomimage',
            name='caption',
        ),
        migrations.AlterField(
            model_name='room',
            name='amenities',
            field=models.ManyToManyField(blank=True, to='pms.property'),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='max_adults',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='room',
            name='max_children',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('Deluxe', 'Deluxe'), ('Suite', 'Suite')], max_length=20),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='image',
            field=models.ImageField(upload_to='rooms/'),
        ),
        migrations.AlterField(
            model_name='roomunit',
            name='room_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='roomunit',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied'), ('Dirty', 'Dirty'), ('Reserved', 'Reserved'), ('Cleaning', 'Cleaning'), ('Maintenance', 'Maintenance')], default='Available', max_length=20),
        ),
        migrations.RemoveField(
            model_name='roomunit',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='roomunit',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='roomunit',
            name='last_cleaned',
        ),
        migrations.RemoveField(
            model_name='roomunit',
            name='notes',
        ),
    ]
