# Generated by Django 6.0.4 on 2026-04-17 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0004_guest_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='room',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='room_unit',
        ),
        migrations.DeleteModel(
            name='Guest',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
