# Generated by Django 6.0.4 on 2026-04-18 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0007_remove_booking_hotel_remove_guest_hotel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='guest',
        ),
    ]
