# Generated by Django 6.0.4 on 2026-04-18 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0008_remove_booking_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pms.guest'),
        ),
    ]
