# Generated by Django 5.1.6 on 2026-04-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0010_alter_booking_id_alter_guest_id_alter_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='guest_token',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
