# Generated by Django 5.1.6 on 2026-04-29 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0012_alter_booking_id_alter_guest_id_alter_payment_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestIDPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='guest_ids/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_photos', to='pms.guest')),
            ],
        ),
    ]
