# Generated by Django 5.1.6 on 2026-05-15 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_subscriptionplan_tagline'),
        ('pms', '0013_guestidphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='checked_in_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings_checked_in', to='accounts.staff'),
        ),
        migrations.AddField(
            model_name='booking',
            name='checked_out_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings_checked_out', to='accounts.staff'),
        ),
    ]
