# Generated by Django 5.1.6 on 2026-05-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0014_booking_checked_in_by_booking_checked_out_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='custom_room_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('Deluxe', 'Deluxe'), ('Suite', 'Suite'), ('Custom', 'Custom')], max_length=20),
        ),
    ]
