# Generated by Django 5.1.6 on 2026-06-04 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0016_payment_amount_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonalRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(blank=True, max_length=100)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasonal_rates', to='pms.room')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
    ]
