# Generated by Django 5.1.6 on 2026-06-05 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0017_seasonalrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonalrate',
            name='notes',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='seasonalrate',
            name='tag',
            field=models.CharField(blank=True, default='base', max_length=100),
        ),
    ]
