# Generated by Django 6.0.4 on 2026-04-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_hotel_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='schema_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
