# Generated by Django 6.0.4 on 2026-04-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_department_alter_rolepermission_role_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='staff',
            unique_together={('hotel', 'employee_id')},
        ),
    ]
