# Generated by Django 5.1.6 on 2026-05-02 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_amenity_id_alter_department_id_alter_hotel_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='is_setup_complete',
            field=models.BooleanField(default=False),
        ),
    ]
