# Generated by Django 5.1.6 on 2026-05-02 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_hotel_is_setup_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='hotel_logos/'),
        ),
    ]
