# Generated by Django 5.1.6 on 2026-05-08 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_amenity_amenity_type_amenity_is_core_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='is_on_trial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='subscription_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotels', to='accounts.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='subscription_status',
            field=models.CharField(choices=[('inactive', 'Inactive'), ('trial', 'Trial'), ('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended')], default='inactive', max_length=20),
        ),
        migrations.AddField(
            model_name='hotel',
            name='trial_days',
            field=models.PositiveIntegerField(default=14),
        ),
        migrations.AddField(
            model_name='hotel',
            name='trial_eligible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='trial_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='trial_granted_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='trial_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_trial_plan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='trial_days',
            field=models.PositiveIntegerField(default=14),
        ),
    ]
