# Generated by Django 5.1.6 on 2026-05-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_hotel_is_on_trial_hotel_subscription_expiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='tagline',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
