# Generated by Django 5.1.6 on 2026-05-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_subscriptionplan_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='id_proof_image',
            field=models.ImageField(blank=True, help_text='Uploaded ID proof image/document', null=True, upload_to='staff_id_proofs/'),
        ),
        migrations.AddField(
            model_name='staff',
            name='id_proof_number',
            field=models.CharField(blank=True, help_text='ID proof number (e.g., Aadhaar number, PAN number)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='id_proof_type',
            field=models.CharField(blank=True, choices=[('aadhaar', 'Aadhaar Card'), ('pan', 'PAN Card'), ('passport', 'Passport'), ('driving_license', 'Driving License'), ('voter_id', 'Voter ID'), ('other', 'Other')], help_text='Type of ID proof provided', max_length=50, null=True),
        ),
    ]
