# Generated by Django 5.1.6 on 2026-05-22 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_staff_id_proof_image_staff_id_proof_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='modules_manually_configured',
            field=models.BooleanField(default=False),
        ),
    ]
