# Generated by Django 5.1.6 on 2026-05-25 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_hotel_modules_manually_configured'),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectedHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('owner_name', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('property_type', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('schema_name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='rejected_hotel_images/')),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(auto_now_add=True)),
                ('rejected_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
