# Generated by Django 5.1.6 on 2026-05-25 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_rejectedhotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
