# Generated by Django 5.1.6 on 2026-05-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_subscriptionplan_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='trial_days',
            field=models.PositiveIntegerField(default=14, help_text='Default trial duration for this plan in days'),
        ),
    ]
