# Generated by Django 5.1.6 on 2026-05-27 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_staff_address_staff_dob_staff_emergency_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='bank_account',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='esi_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='ifsc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='pf_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
