# Generated by Django 5.1.6 on 2026-04-26 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('pms', '0012_alter_booking_id_alter_guest_id_alter_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundryorder',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pms.booking'),
        ),
    ]
