# Generated by Django 5.1.6 on 2026-05-12 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_assetcategory_expensecategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancelog',
            name='custom_asset',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='duration',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='labour_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='parts_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='parts_replaced',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('critical', 'Critical')], default='low', max_length=20),
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='inventory.hotelasset'),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='maintenance_type',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('reactive', 'Reactive / Breakdown'), ('preventive', 'Preventive'), ('inspection', 'Inspection'), ('deep_service', 'Deep Service'), ('calibration', 'Calibration'), ('cleaning', 'Cleaning'), ('replacement', 'Part Replacement')], default='scheduled', max_length=30),
        ),
    ]
