# Generated by Django 5.1.6 on 2026-05-13 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_subscriptionplan_tagline'),
        ('inventory', '0004_maintenancelog_custom_asset_maintenancelog_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancelog',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_logs', to='accounts.department'),
        ),
    ]
