# Generated by Django 5.1.6 on 2026-05-13 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_maintenancelog_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='maintenance_log',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense', to='inventory.maintenancelog'),
        ),
    ]
