# Generated by Django 5.1.6 on 2026-05-16 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_subscriptionplan_tagline'),
        ('inventory', '0006_expense_maintenance_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundryorder',
            name='delivered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivered_orders', to='accounts.staff'),
        ),
    ]
