# Generated by Django 5.1.6 on 2026-05-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_laundryorder_delivered_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcategory',
            name='is_restaurant',
            field=models.BooleanField(default=False),
        ),
    ]
