# Generated by Django 5.1.6 on 2026-05-19 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_itemcategory_is_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcategory',
            name='is_restaurant',
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='category_type',
            field=models.CharField(choices=[('housekeeping', 'Housekeeping'), ('restaurant', 'Restaurant'), ('general', 'General'), ('custom', 'Custom')], default='general', max_length=20),
        ),
    ]
