# Generated by Django 5.1.6 on 2026-05-19 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_remove_itemcategory_is_restaurant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcategory',
            name='category_type',
        ),
    ]
