# Generated by Django 5.1.6 on 2026-06-01 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_staff_bank_account_staff_esi_number_staff_ifsc_and_more'),
        ('inventory', '0010_remove_itemcategory_category_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelLinenBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rooms', models.CharField(max_length=100)),
                ('sent_to_laundry', models.CharField(blank=True, max_length=200)),
                ('batch_type', models.CharField(choices=[('post_checkout', 'Post-checkout linen'), ('daily_refresh', 'Daily refresh'), ('deep_clean', 'Deep clean'), ('damage_wash', 'Damage/stain wash')], default='post_checkout', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('dispatched', 'Dispatched'), ('received', 'Received')], default='dispatched', max_length=20)),
                ('dispatched_at', models.DateTimeField(auto_now_add=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('dispatched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linen_dispatched', to='accounts.staff')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linen_received', to='accounts.staff')),
            ],
            options={
                'ordering': ['-dispatched_at'],
            },
        ),
        migrations.CreateModel(
            name='HotelLinenBatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_label', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('received', models.BooleanField(default=False)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.hotellinenbatch')),
            ],
        ),
    ]
