# Generated by Django 5.1.6 on 2026-06-01 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_hotellinenbatch_hotellinenbatchitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotellinenbatchitem',
            name='recieved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
