# Generated by Django 5.1.6 on 2026-06-01 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_hotellinenbatchitem_recieved_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotellinenbatchitem',
            old_name='recieved_at',
            new_name='received_at',
        ),
    ]
