# Generated by Django 5.1.6 on 2026-06-01 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_rename_recieved_at_hotellinenbatchitem_received_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinenMissingReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'label'],
            },
        ),
        migrations.RemoveField(
            model_name='hotellinenbatchitem',
            name='received',
        ),
        migrations.AddField(
            model_name='hotellinenbatchitem',
            name='damaged_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hotellinenbatchitem',
            name='missing_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hotellinenbatchitem',
            name='missing_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hotellinenbatchitem',
            name='missing_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inventory.linenmissingreason'),
        ),
    ]
