# Generated by Django 5.1.6 on 2026-06-01 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_linenmissingreason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotellinenbatch',
            name='received_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
