# Generated by Django 5.1.6 on 2026-06-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_hotellinenbatch_received_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotellinenbatch',
            name='received_quantity',
        ),
        migrations.AddField(
            model_name='hotellinenbatchitem',
            name='received_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
