# Generated by Django 5.1.6 on 2026-06-02 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_remove_hotellinenbatch_received_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotellinenbatch',
            name='batch_type',
        ),
        migrations.RemoveField(
            model_name='hotellinenbatch',
            name='rooms',
        ),
        migrations.AddField(
            model_name='hotellinenbatch',
            name='laundry_contact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hotellinenbatch',
            name='laundry_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='hotellinenbatchitem',
            name='item_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='hotellinenbatch',
            name='status',
            field=models.CharField(choices=[('dispatched', 'Dispatched'), ('partial', 'Partially Received'), ('received', 'Received')], default='dispatched', max_length=20),
        ),
    ]
