# Generated by Django 5.1.6 on 2026-06-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_remove_hotellinenbatch_batch_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='source',
            field=models.CharField(choices=[('purchase_order', 'Purchase Order'), ('direct', 'Direct Purchase'), ('manual', 'Manual Entry'), ('laundry', 'Laundry Payment')], default='manual', max_length=20),
        ),
    ]
