# Generated by Django 5.1.6 on 2026-06-02 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_alter_expense_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='linen_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='inventory.hotellinenbatch'),
        ),
        migrations.AddField(
            model_name='hotellinenbatch',
            name='expected_return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
