# Generated by Django 5.1.6 on 2026-04-25 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0012_alter_booking_id_alter_guest_id_alter_payment_id_and_more'),
        ('restaurant', '0002_restaurantorder_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantorder',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_orders', to='pms.booking'),
        ),
    ]
