# Generated by Django 5.1.6 on 2026-04-25 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_restaurantorder_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('reservation_time', models.DateTimeField()),
                ('guests_count', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('seated', 'Seated'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='reserved', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.table')),
            ],
        ),
        migrations.AddField(
            model_name='restaurantorder',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.tablereservation'),
        ),
    ]
