# Generated by Django 5.1.6 on 2026-05-01 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
    ]
