# Generated by Django 5.1.6 on 2026-05-05 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_payroll_esi_amount_payroll_incentive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='custom_deductions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='payroll',
            name='custom_earnings',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
