# Generated by Django 5.1.6 on 2026-05-05 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_hotel_logo'),
        ('hotel', '0005_shifttemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='custom_color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='custom_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='custom_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='custom_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shifttemplate',
            name='color',
            field=models.CharField(default='#1a65f5', max_length=10),
        ),
        migrations.AddField(
            model_name='shifttemplate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='shift',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Evening', 'Evening'), ('Night', 'Night'), ('Custom', 'Custom')], max_length=20),
        ),
        migrations.AlterField(
            model_name='shifttemplate',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_templates', to='accounts.hotel'),
        ),
        migrations.AlterField(
            model_name='shifttemplate',
            name='shift_name',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Evening', 'Evening'), ('Night', 'Night'), ('Custom', 'Custom')], max_length=50),
        ),
    ]
