# Generated by Django 5.1.6 on 2026-05-18 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_subscriptionplan_tagline'),
        ('hotel', '0007_message_messageattachment_messagethread_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeFinancialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pf_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('esi_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('loan_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('advance_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gratuity_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.staff')),
            ],
        ),
        migrations.CreateModel(
            name='FinalSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_working_day', models.DateField()),
                ('pending_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('leave_encashment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gratuity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pf_payable', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.staff')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_type', models.CharField(choices=[('earning', 'Earning'), ('deduction', 'Deduction')], max_length=10)),
                ('source', models.CharField(choices=[('basic', 'Basic Salary'), ('overtime', 'Overtime'), ('bonus', 'Bonus'), ('incentive', 'Incentive'), ('hra', 'HRA'), ('da', 'DA'), ('ta', 'Travel Allowance'), ('medical', 'Medical Allowance'), ('special', 'Special Allowance'), ('custom', 'Custom'), ('leave', 'Leave/Absent Deduction'), ('pf', 'PF (Employee)'), ('esi', 'ESI (Employee)'), ('pt', 'Professional Tax'), ('tax', 'Tax/TDS'), ('loan', 'Loan Deduction'), ('advance', 'Salary Advance'), ('uniform', 'Uniform Deduction')], max_length=30)),
                ('label', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pct', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('pct_base', models.CharField(blank=True, default='', max_length=20)),
                ('is_auto', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='hotel.payroll')),
            ],
            options={
                'ordering': ['line_type', 'order', 'id'],
            },
        ),
    ]
